openapi: 3.0.0

info:
  title: appropriate-filetering-api
  version: 0.0.1

servers:
  - url: https://endpoint.ainize.ai/minsulee2/primality-test/

paths:
  /chk:
    post:
      parameters:
        - name: number
          in: query
          required: true
          allowReserved: true
      responses:
        '200':
          content:
            applicatioin/json:
              schema:
                type: string
                properties:
                  result:
                    type: string
        '400':
          description: Bad Request Error
        default:
          description: Unexpected Error